before_build:
  - nuget restore
deploy:
  release: ReferencePatcher-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: tUj4kkwdAoUW02afvChhaNIKQO8S4dgUat24w/9J/bq2Lp35GObwxlg0mYALdP/g # your encrypted token from GitHub
  artifact: ReferencePatcher/Release/ReferencePatcher.vsix
  draft: false
  prerelease: false
  force_update: true
  tag: $(APPVEYOR_REPO_TAG_NAME)
  on:
    appveyor_repo_tag: true 