image: Visual Studio 2017
before_build:
  - cmd: nuget restore
  - ps: >-
        Add-Content GitVersion.yml "assembly-informational-format: '{Major}.{Minor}.{Patch}.$env:appveyor_build_version'"
configuration:
  - Debug
  - Release
artifacts:
  - path: ReferencePatcher/bin/Release/ReferencePatcher.vsix
    name: ReferencePatcher

deploy:
  release: ReferencePatcher-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: tUj4kkwdAoUW02afvChhaNIKQO8S4dgUat24w/9J/bq2Lp35GObwxlg0mYALdP/g # your encrypted token from GitHub
  artifact: ReferencePatcher
  draft: false
  prerelease: false
  force_update: true
  tag: $(APPVEYOR_REPO_TAG_NAME)
  on:
    appveyor_repo_tag: true
    configuration: release 